scrape_configs:
  - job_name: 'microservice-resource'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus' ##prometheus endpoint
    static_configs:
      - targets: ['localhost:9090'] ## host and port for your mis
  - job_name: 'microservice-song'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8580']
  - job_name: 'microservice-resource-processor'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:9292']